name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: download deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: check format
        run: deno fmt --check

      - name: check linting
        run: deno lint

      - name: run tests
        run: deno task test

      - name: pretend to publish package
        run: deno publish --dry-run
